import React from 'react';
import './styles/DiagnosisModal.css'; // Import the updated CSS

const DiagnosisModal = ({ onClose }) => {
  const handleDownload = () => {
    // Logic to handle download (dummy implementation)
    alert('Download report functionality coming soon!');
  };

  return (
    <div className="modal-overlay">
      <div className="modal-container">
        {/* Modal header */}
        <div className="modal-header">
          <h2 className="modal-title">Clarivex.AI Diagnostic Report</h2>
          <span className="modal-close" onClick={onClose}>&times;</span>
        </div>

        {/* Scrollable report content */}
        <div className="modal-body">
          <div className="report-content">
            <p>
              <strong>Report ID:</strong> DX-2024-05-0034<br/>
              <strong>Generated By:</strong> Clarivex.AI Diagnostic Tool<br/>
              <strong>Date:</strong> October 5, 2024<br/>
              <strong>Facility:</strong> Metropolitan Neurology Clinic<br/>
              <strong>Department:</strong> Neurology Department<br/>
              <strong>Consulting Physician:</strong> Dr. Sam Harris, MD
            </p>

            <h3>Patient Information</h3>
            <p>
              <strong>Name:</strong> John Doe<br/>
              <strong>Age:</strong> 52<br/>
              <strong>Gender:</strong> Male<br/>
              <strong>Date of Birth:</strong> February 14, 1972<br/>
              <strong>Patient ID:</strong> P-12978432<br/>
              <strong>Date of Visit:</strong> October 5, 2024<br/>
              <strong>Referring Physician:</strong> Dr. Sam Harris, MD
            </p>

            <h3>Imaging Information</h3>
            <p>
              <strong>Modality:</strong> MRI of the Brain with Contrast<br/>
              <strong>File Reference:</strong> MRI-BRAIN-WITH-CONTRAST-0001.jpg<br/>
              <strong>Date of Scan:</strong> October 4, 2024
            </p>

            <h3>MRI Findings</h3>
            <p>
              <strong>Ventricular System:</strong><br/>
              Lateral and third ventricles normal, no abnormal enlargement.<br/>
              No hydrocephalus or midline shift.
            </p>
            <p>
              <strong>Cerebral Parenchyma:</strong><br/>
              Mild hyperintensities in periventricular white matter (small vessel ischemic changes).<br/>
              No mass effect or cortical atrophy.
            </p>
            <p>
              <strong>Basal Ganglia & Thalami:</strong><br/>
              No abnormalities or hemorrhages.
            </p>
            <p>
              <strong>Posterior Fossa:</strong><br/>
              Additional findings here...
            </p>
          </div>
        </div>

        {/* Footer with download button */}
        <div className="modal-footer">
          <button className="download-button" onClick={handleDownload}>
            Download Report
          </button>
        </div>
      </div>
    </div>
  );
};

export default DiagnosisModal;
