import React from 'react';
import './styles/DiagnosisModal.css'; // Import the updated CSS

const DiagnosisModal = ({ onClose }) => {
  const handleDownload = () => {
    // Logic to handle download (dummy implementation)
    alert('Download report functionality coming soon!');
  };

  return (
    <div className="modal-overlay">
      <div className="modal-container">
        {/* Modal header */}
        <div className="modal-header">
          <h2 className="modal-title">Clarivex.AI Diagnostic Report</h2>
          <span className="modal-close" onClick={onClose}>&times;</span>
        </div>

        {/* Scrollable report content */}
        <div className="modal-body">
          <div className="report-content">
            <p>
              <strong>Report ID:</strong> DX-2024-10-0523<br/>
              <strong>Generated By:</strong> Clarivex.AI Diagnostic Tool<br/>
              <strong>Date:</strong> October 5, 2024<br/>
              <strong>Facility:</strong> Metropolitan Dermatology Clinic<br/>
              <strong>Department:</strong> Dermatology Department<br/>
              <strong>Consulting Physician:</strong> Dr. Sam Harris, MD
            </p>

            <h3>Patient Information</h3>
            <p>
              <strong>Name:</strong> John Doe<br/>
              <strong>Age:</strong> 52<br/>
              <strong>Gender:</strong> Male<br/>
              <strong>Date of Birth:</strong> February 14, 1972<br/>
              <strong>Patient ID:</strong> P-12978432<br/>
              <strong>Date of Visit:</strong> October 5, 2024<br/>
              <strong>Referring Physician:</strong> Dr. Sam Harris, MD
            </p>

            <h3>Imaging Information</h3>
            <p>
              <strong>Modality:</strong> Skin Biopsy and Dermoscopy<br/>
              <strong>File Reference:</strong> DERMOSCOPY-SKIN-BIOPSY-0001.jpg<br/>
              <strong>Date of Procedure:</strong> October 4, 2024
            </p>

            <h3>Findings</h3>
            <p>
              <strong>Skin Lesions:</strong><br/>
              Multiple hyperpigmented macules and patches noted on the upper back and forearms.<br/>
              Lesions range in size from 3mm to 7mm, irregular borders, with some evidence of crusting.
            </p>
            <p>
              <strong>Biopsy Results:</strong><br/>
              Skin biopsy of the lesion on the right forearm showed features consistent with actinic keratosis.<br/>
              No evidence of invasive squamous cell carcinoma at this time.
            </p>
            <p>
              <strong>Dermoscopic Findings:</strong><br/>
              Dermoscopy revealed irregular pigment network, dotted vessels, and areas of blue-white veil on multiple lesions.<br/>
              Further monitoring recommended for changes in size, color, or texture of lesions.
            </p>
            <p>
              <strong>Impression:</strong><br/>
              Actinic keratosis with potential for malignant transformation if untreated.<br/>
              Close follow-up advised.
            </p>

            <h3>Recommendations</h3>
            <p>
              - Regular monitoring of lesions with dermoscopy every 6 months.<br/>
              - Application of topical 5-fluorouracil cream to areas of actinic keratosis.<br/>
              - Avoid prolonged sun exposure and use broad-spectrum sunscreen (SPF 50+) daily.<br/>
              - Follow-up appointment in 3 months for reassessment.
            </p>
          </div>
        </div>

        {/* Footer with download button */}
        <div className="modal-footer">
          <button className="download-button" onClick={handleDownload}>
            Download Report
          </button>
        </div>
      </div>
    </div>
  );
};

export default DiagnosisModal;
